import type { ComponentType } from "react";
import {
  AirVent,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowUpDown,
  BarChart3,
  BatteryCharging,
  Brush,
  Calendar,
  CalendarDays,
  CheckCircle,
  ChefHat,
  ChevronDown,
  ChevronRight,
  Clock,
  Coffee,
  Computer,
  CookingPot,
  DollarSign,
  DoorOpen,
  Droplets,
  Fan,
  Flame,
  Gamepad2,
  HelpCircle,
  History,
  Home,
  Lamp,
  LampCeiling,
  Laptop,
  Lightbulb,
  Microwave,
  Minus,
  Monitor,
  PlugZap,
  Plus,
  Refrigerator,
  RotateCcw,
  Router,
  Save,
  Search,
  ShowerHead,
  Snowflake,
  Sparkles,
  Sun,
  Target,
  Trash2,
  Tv,
  UserCog,
  WashingMachine,
  Waves,
  Wind,
  Wrench,
  X,
  Zap,
} from "lucide-react";

export type IconComponent = ComponentType<{ size?: number; className?: string }>;

/**
 * Registry estático dos ícones Lucide efetivamente usados pelo app.
 *
 * OBSERVAÇÃO (otimização de bundle): anteriormente o LucideIcon usava
 * `import * as Icons from "lucide-react"`, o que embalava TODOS os ~3.4k
 * ícones do pacote no bundle (~529 kB). Como o app resolve ícones
 * dinamicamente por nome (catálogo de aparelhos, categorias, UI), optamos
 * por um registry explícito com apenas os ~55 ícones usados, reduzindo o
 * chunk para alguns kB.
 *
 * Ao adicionar um novo ícone no catálogo (src/data/appliance-icons.ts) ou
 * na UI, importe-o aqui e inclua no registry.
 *
 * Exportado também para o teste src/test/icon-registry.test.ts, que garante
 * que todo ícone resolvido pelo catálogo existe neste registry (evitando o
 * bug de ícone inexistente renderizando null em silêncio, ex: Vacuum).
 */
export const ICON_REGISTRY: Record<string, IconComponent> = {
  AirVent,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowUpDown,
  BarChart3,
  BatteryCharging,
  Brush,
  Calendar,
  CalendarDays,
  CheckCircle,
  ChefHat,
  ChevronDown,
  ChevronRight,
  Clock,
  Coffee,
  Computer,
  CookingPot,
  DollarSign,
  DoorOpen,
  Droplets,
  Fan,
  Flame,
  Gamepad2,
  HelpCircle,
  History,
  Home,
  Lamp,
  LampCeiling,
  Laptop,
  Lightbulb,
  Microwave,
  Minus,
  Monitor,
  PlugZap,
  Plus,
  Refrigerator,
  RotateCcw,
  Router,
  Save,
  Search,
  ShowerHead,
  Snowflake,
  Sparkles,
  Sun,
  Target,
  Trash2,
  Tv,
  UserCog,
  WashingMachine,
  Waves,
  Wind,
  Wrench,
  X,
  Zap,
};
